[build]

command = "composer build"
publish = "dist"

[[plugins]]
package = "@netlify/plugin-sitemap"
[[plugins]]
package = "@netlify/plugin-lighthouse"

[[redirects]]
from="/posts/*"
to="/articles/:splat"
[[redirects]]
from="/writing/*"
to="/articles/:splat"

[[redirects]]
from="/presentations/*"
to="/speaking/:splat"
[[redirects]]
from="/decks/*"
to="/speaking/:splat"

[[redirects]]
from="/projects/*"
to="/work/:splat"

[[redirects]]
from="/articles/fiddling-with-asp-dotnet-core-and-fsharp-with-suave"
to="/articles/technical-deep-dives/fiddling-with-asp-dotnet-core-and-fsharp-with-suave"
[[redirects]]
from="/articles/asp-dotnet-core-webapi-in-azure-app-service"
to="/articles/strategic-insights/asp-dotnet-core-webapi-in-azure-app-service"
[[redirects]]
from="/articles/cross-compiling-rust-applications-for-the-onion-omega2-from-macos"
to="/articles/technical-deep-dives/cross-compiling-rust-applications-for-the-onion-omega2-from-macos"
[[redirects]]
from="/articles/exploring-fsharp-with-dotnet-core-and-kestrel"
to="/articles/technical-deep-dives/exploring-fsharp-with-dotnet-core-and-kestrel"
[[redirects]]
from="/articles/simple-php-socket-programming"
to="/articles/technical-deep-dives/simple-php-socket-programming"
[[redirects]]
from="/articles/functors-applicatives-and-monads-in-elixir"
to="/articles/technical-deep-dives/functors-applicatives-and-monads-in-elixir"
[[redirects]]
from="/articles/pitstop-with-the-elixir-genevent-module"
to="/articles/technical-deep-dives/pitstop-with-the-elixir-genevent-module"
[[redirects]]
from="/articles/wordpress-docker-and-you"
to="/articles/leadership-and-management/wordpress-docker-and-you"
[[redirects]]
from="/articles/im-learning-haskell-for-real-this-time"
to="/articles/industry-analysis/im-learning-haskell-for-real-this-time"
[[redirects]]
from="/articles/application-deployment"
to="/articles/strategic-insights/application-deployment"
[[redirects]]
from="/articles/review-getting-started-with-phalcon"
to="/articles/industry-analysis/review-getting-started-with-phalcon"
[[redirects]]
from="/articles/migrate-your-site-without-killing-your-search-engine-presence"
to="/articles/leadership-and-management/migrate-your-site-without-killing-your-search-engine-presence"
[[redirects]]
from="/articles/writing-api-wrappers-with-elixir"
to="/articles/technical-deep-dives/writing-api-wrappers-with-elixir"
[[redirects]]
from="/articles/implementing-user-authentication-with-bcrypt-in-chicagoboss"
to="/articles/technical-deep-dives/implementing-user-authentication-with-bcrypt-in-chicagoboss"
[[redirects]]
from="/articles/acvte"
to="/articles/technical-deep-dives/acvte"
[[redirects]]
from="/articles/migrating-to-acvte"
to="/articles/technical-deep-dives/migrating-to-acvte"
[[redirects]]
from="/articles/chicagoboss"
to="/articles/technical-deep-dives/chicagoboss"
[[redirects]]
from="/articles/im-already-tired-of-rails-already"
to="/articles/industry-analysis/im-already-tired-of-rails-already"
[[redirects]]
from="/articles/vagrant-is-awesome"
to="/articles/strategic-insights/vagrant-is-awesome"
[[redirects]]
from="/articles/migrating-from-mysql-server-to-percona-server"
to="/articles/strategic-insights/migrating-from-mysql-server-to-percona-server"
[[redirects]]
from="/articles/using-obtvse2"
to="/articles/technical-deep-dives/using-obtvse2"
[[redirects]]
from="/articles/linux-and-net-should-be-friends"
to="/articles/industry-analysis/linux-and-net-should-be-friends"
[[redirects]]
from="/articles/installing-nginx-percona-php-fpm-with-homebrew-on-mountain-lion"
to="/articles/technical-deep-dives/installing-nginx-percona-php-fpm-with-homebrew-on-mountain-lion"
[[redirects]]
from="/speaking/drive-growth-with-effective-partnerships"
to="/speaking/strategic-insights/drive-growth-with-effective-partnerships"
[[redirects]]
from="/speaking/dont-leave-cash-in-the-cart"
to="/speaking/strategic-insights/dont-leave-cash-in-the-cart"
[[redirects]]
from="/speaking/http-and-me"
to="/speaking/technical-deep-dives/http-and-me"
[[redirects]]
from="/speaking/beginners-hands-on-with-haskell"
to="/speaking/technical-deep-dives/beginners-hands-on-with-haskell"
[[redirects]]
from="/speaking/plug-friend-of-web-developers"
to="/speaking/technical-deep-dives/plug-friend-of-web-developers"
[[redirects]]
from="/speaking/introduction-to-testing-with-exunit"
to="/speaking/technical-deep-dives/introduction-to-testing-with-exunit"
[[redirects]]
from="/speaking/functional-programming-principles-in-elixir"
to="/speaking/technical-deep-dives/functional-programming-principles-in-elixir"
[[redirects]]
from="/speaking/go-an-introduction"
to="/speaking/technical-deep-dives/go-an-introduction"
