[build]
command = "composer build"
publish = "dist"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  exclude = [
    './dist/articles/_drafts/**/*'
  ]

[[plugins]]
package = "@netlify/plugin-lighthouse"



[[redirects]]
from="/posts/*"
to="/articles/:splat"
[[redirects]]
from="/writing/*"
to="/articles/:splat"
[[redirects]]
from="/presentations/*"
to="/speaking/:splat"
[[redirects]]
from="/decks/*"
to="/speaking/:splat"
[[redirects]]
from="/projects/*"
to="/work/:splat"
[[redirects]]
from="/articles/fiddling-with-asp-dotnet-core-and-fsharp-with-suave"
to="/articles/technical-deep-dives/fiddling-with-asp-dotnet-core-and-fsharp-with-suave"
[[redirects]]
from="/articles/asp-dotnet-core-webapi-in-azure-app-service"
to="/articles/strategic-insights/asp-dotnet-core-webapi-in-azure-app-service"
[[redirects]]
from="/articles/cross-compiling-rust-applications-for-the-onion-omega2-from-macos"
to="/articles/technical-deep-dives/cross-compiling-rust-applications-for-the-onion-omega2-from-macos"
[[redirects]]
from="/articles/exploring-fsharp-with-dotnet-core-and-kestrel"
to="/articles/technical-deep-dives/exploring-fsharp-with-dotnet-core-and-kestrel"
[[redirects]]
from="/articles/simple-php-socket-programming"
to="/articles/technical-deep-dives/simple-php-socket-programming"
[[redirects]]
from="/articles/functors-applicatives-and-monads-in-elixir"
to="/articles/technical-deep-dives/functors-applicatives-and-monads-in-elixir"
[[redirects]]
from="/articles/pitstop-with-the-elixir-genevent-module"
to="/articles/technical-deep-dives/pitstop-with-the-elixir-genevent-module"
[[redirects]]
from="/articles/wordpress-docker-and-you"
to="/articles/leadership-and-management/wordpress-docker-and-you"
[[redirects]]
from="/articles/im-learning-haskell-for-real-this-time"
to="/articles/industry-analysis/im-learning-haskell-for-real-this-time"
[[redirects]]
from="/articles/application-deployment"
to="/articles/strategic-insights/application-deployment"
[[redirects]]
from="/articles/review-getting-started-with-phalcon"
to="/articles/industry-analysis/review-getting-started-with-phalcon"
[[redirects]]
from="/articles/migrate-your-site-without-killing-your-search-engine-presence"
to="/articles/leadership-and-management/migrate-your-site-without-killing-your-search-engine-presence"
[[redirects]]
from="/articles/writing-api-wrappers-with-elixir"
to="/articles/technical-deep-dives/writing-api-wrappers-with-elixir"
[[redirects]]
from="/articles/implementing-user-authentication-with-bcrypt-in-chicagoboss"
to="/articles/technical-deep-dives/implementing-user-authentication-with-bcrypt-in-chicagoboss"
[[redirects]]
from="/articles/acvte"
to="/articles/technical-deep-dives/acvte"
[[redirects]]
from="/articles/migrating-to-acvte"
to="/articles/technical-deep-dives/migrating-to-acvte"
[[redirects]]
from="/articles/chicagoboss"
to="/articles/technical-deep-dives/chicagoboss"
[[redirects]]
from="/articles/im-already-tired-of-rails-already"
to="/articles/industry-analysis/im-already-tired-of-rails-already"
[[redirects]]
from="/articles/vagrant-is-awesome"
to="/articles/strategic-insights/vagrant-is-awesome"
[[redirects]]
from="/articles/migrating-from-mysql-server-to-percona-server"
to="/articles/strategic-insights/migrating-from-mysql-server-to-percona-server"
[[redirects]]
from="/articles/using-obtvse2"
to="/articles/technical-deep-dives/using-obtvse2"
[[redirects]]
from="/articles/linux-and-net-should-be-friends"
to="/articles/industry-analysis/linux-and-net-should-be-friends"
[[redirects]]
from="/articles/installing-nginx-percona-php-fpm-with-homebrew-on-mountain-lion"
to="/articles/technical-deep-dives/installing-nginx-percona-php-fpm-with-homebrew-on-mountain-lion"
[[redirects]]
from="/speaking/drive-growth-with-effective-partnerships"
to="/speaking/strategic-insights/drive-growth-with-effective-partnerships"
[[redirects]]
from="/speaking/dont-leave-cash-in-the-cart"
to="/speaking/strategic-insights/dont-leave-cash-in-the-cart"
[[redirects]]
from="/speaking/http-and-me"
to="/speaking/technical-deep-dives/http-and-me"
[[redirects]]
from="/speaking/beginners-hands-on-with-haskell"
to="/speaking/technical-deep-dives/beginners-hands-on-with-haskell"
[[redirects]]
from="/speaking/plug-friend-of-web-developers"
to="/speaking/technical-deep-dives/plug-friend-of-web-developers"
[[redirects]]
from="/speaking/introduction-to-testing-with-exunit"
to="/speaking/technical-deep-dives/introduction-to-testing-with-exunit"
[[redirects]]
from="/speaking/functional-programming-principles-in-elixir"
to="/speaking/technical-deep-dives/functional-programming-principles-in-elixir"
[[redirects]]
from="/speaking/go-an-introduction"
to="/speaking/technical-deep-dives/go-an-introduction"
[[redirects]]
from="/articles/technical-deep-dives/fiddling-with-asp-dotnet-core-and-fsharp-with-suave"
to="/archive/2017/fiddling-with-asp-dotnet-core-and-fsharp-with-suave"
[[redirects]]
from="/articles/strategic-insights/asp-dotnet-core-webapi-in-azure-app-service"
to="/archive/2017/asp-dotnet-core-webapi-in-azure-app-service"
[[redirects]]
from="/articles/technical-deep-dives/cross-compiling-rust-applications-for-the-onion-omega2-from-macos"
to="/archive/2017/cross-compiling-rust-applications-for-the-onion-omega2-from-macos"
[[redirects]]
from="/articles/technical-deep-dives/exploring-fsharp-with-dotnet-core-and-kestrel"
to="/archive/2016/exploring-fsharp-with-dotnet-core-and-kestrel"
[[redirects]]
from="/articles/technical-deep-dives/simple-php-socket-programming"
to="/archive/2016/simple-php-socket-programming"
[[redirects]]
from="/articles/technical-deep-dives/functors-applicatives-and-monads-in-elixir"
to="/archive/2015/functors-applicatives-and-monads-in-elixir"
[[redirects]]
from="/articles/technical-deep-dives/pitstop-with-the-elixir-genevent-module"
to="/archive/2015/pitstop-with-the-elixir-genevent-module"
[[redirects]]
from="/articles/technical-deep-dives/wordpress-docker-and-you"
to="/archive/2015/wordpress-docker-and-you"
[[redirects]]
from="/articles/industry-analysis/im-learning-haskell-for-real-this-time"
to="/archive/2014/im-learning-haskell-for-real-this-time"
[[redirects]]
from="/articles/strategic-insights/application-deployment"
to="/archive/2014/application-deployment"
[[redirects]]
from="/articles/industry-analysis/review-getting-started-with-phalcon"
to="/archive/2014/review-getting-started-with-phalcon"
[[redirects]]
from="/articles/technical-deep-dives/migrate-your-site-without-killing-your-search-engine-presence"
to="/archive/2013/migrate-your-site-without-killing-your-search-engine-presence"
[[redirects]]
from="/articles/technical-deep-dives/writing-api-wrappers-with-elixir"
to="/archive/2013/writing-api-wrappers-with-elixir"
[[redirects]]
from="/articles/technical-deep-dives/implementing-user-authentication-with-bcrypt-in-chicagoboss"
to="/archive/2013/implementing-user-authentication-with-bcrypt-in-chicagoboss"
[[redirects]]
from="/articles/technical-deep-dives/acvte"
to="/archive/2013/acvte"
[[redirects]]
from="/articles/technical-deep-dives/migrating-to-acvte"
to="/archive/2013/migrating-to-acvte"
[[redirects]]
from="/articles/technical-deep-dives/chicagoboss"
to="/archive/2013/chicagoboss"
[[redirects]]
from="/articles/industry-analysis/im-already-tired-of-rails-already"
to="/archive/2013/im-already-tired-of-rails-already"
[[redirects]]
from="/articles/strategic-insights/vagrant-is-awesome"
to="/archive/2013/vagrant-is-awesome"
[[redirects]]
from="/articles/strategic-insights/migrating-from-mysql-server-to-percona-server"
to="/archive/2013/migrating-from-mysql-server-to-percona-server"
[[redirects]]
from="/articles/technical-deep-dives/using-obtvse2"
to="/archive/2013/using-obtvse2"
[[redirects]]
from="/articles/industry-analysis/linux-and-net-should-be-friends"
to="/archive/2013/linux-and-net-should-be-friends"
[[redirects]]
from="/articles/technical-deep-dives/installing-nginx-percona-php-fpm-with-homebrew-on-mountain-lion"
to="/archive/2013/installing-nginx-percona-php-fpm-with-homebrew-on-mountain-lion"
[[redirects]]
from="/speaking/strategic-insights/drive-growth-with-effective-partnerships"
to="/archive/2019/drive-growth-with-effective-partnerships"
[[redirects]]
from="/speaking/strategic-insights/dont-leave-cash-in-the-cart"
to="/archive/2016/dont-leave-cash-in-the-cart"
[[redirects]]
from="/speaking/technical-deep-dives/http-and-me"
to="/archive/2014/http-and-me"
[[redirects]]
from="/speaking/technical-deep-dives/beginners-hands-on-with-haskell"
to="/archive/2016/beginners-hands-on-with-haskell"
[[redirects]]
from="/speaking/technical-deep-dives/plug-friend-of-web-developers"
to="/archive/2016/plug-friend-of-web-developers"
[[redirects]]
from="/speaking/technical-deep-dives/introduction-to-testing-with-exunit"
to="/archive/2015/introduction-to-testing-with-exunit"
[[redirects]]
from="/speaking/technical-deep-dives/functional-programming-principles-in-elixir"
to="/archive/2015/functional-programming-principles-in-elixir"
[[redirects]]
from="/speaking/technical-deep-dives/go-an-introduction"
to="/archive/2014/go-an-introduction"
