[build]

command = "composer build"
publish = "dist"

[[redirects]]
from="/posts/*"
to="/articles/:splat"
[[redirects]]
from="/writing/*"
to="/articles/:splat"

[[redirects]]
from="/presentations/*"
to="/speaking/:splat"
[[redirects]]
from="/decks/*"
to="/speaking/:splat"

[[redirects]]
from="/projects/*"
to="/work/:splat"
